---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shja.nginx.fullname" . }}
  labels:
    app: {{ template "shja.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "shja.nginx.fullname" . }}
data:
  000-default.conf: |
    server {
        listen       80;
        server_name localhost;
        index index.html index.htm;
        {{- if .Values.auth.enabled }}
        auth_basic  "{{ .Values.auth.banner }}";
        auth_basic_user_file "conf.d/htpasswd";
        {{- end }}
        location / {
            root  /var/shja;
            try_files $uri $uri/ $uri.html $uri.xml $uri.jpg $uri.png =404;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root  /usr/share/nginx/html;
        }
    }
  {{- if .Values.auth.enabled }}
  htpasswd: |
    {{ .Values.auth.htpasswd | indent 4 }}
  {{- end }}
