---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shja.fullname" . }}-crontab
  labels:
    app: {{ template "shja.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "shja.fullname" . }}
data:
  root: |
    {{ .Values.schedule }} bash /var/bin/shja.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shja.fullname" . }}-script
  labels:
    app: {{ template "shja.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "shja.fullname" . }}
data:
  shja.sh: |
    #!/usr/bin/env bash
    set -eu
    export LC_ALL=C

    cd /usr/src/app

    #bundle exec ruby exe/{{ .Values.exe }} --log-level info refresh
    {{- if .Values.download.enabled }}
    #bundle exec ruby exe/{{ .Values.exe }} --log-level info download {{ .Values.download.options }}
    {{- end }}
