apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "shja.fullname" . }}
  labels:
    app: {{ template "shja.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "shja.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "shja.name" . }}
        release: {{ .Release.Name }}
        component: {{ template "shja.fullname" . }}
    spec:
      containers:
      - name: shja
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        {{- range $key, $value :=  .Values.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        - name: PONDO_USERNAME
          value: {{ .Values.pondo.username }}
        - name: PONDO_PASSWORD
          value: {{ .Values.pondo.password }}
        - name: PONDO_ANSWER
          value: {{ .Values.pondo.answer }}
        - name: CARIB_USERNAME
          value: {{ .Values.carib.username }}
        - name: CARIB_PASSWORD
          value: {{ .Values.carib.password }}
        - name: CARIB_ANSWER
          value: {{ .Values.carib.answer }}
        - name: PONDO_TARGET_DIR
          value: /var/shja
        - name: CARIB_TARGET_DIR
          value: /var/shja
        - name: PONDO_SELENIUM_URL
          value: http://{{ template "shja.chrome.fullname" . }}:{{ .Values.chrome.service.externalPort }}/wd/hub
        - name: CARIB_SELENIUM_URL
          value: http://{{ template "shja.chrome.fullname" . }}:{{ .Values.chrome.service.externalPort }}/wd/hub
        volumeMounts:
          - name: data
            mountPath: /var/shja
          - name: script
            mountPath: /var/bin/shja.sh
            subPath: shja.sh
          - name: crontab
            mountPath: /var/spool/cron/crontabs/root
            subPath: root
      volumes:
        - name: script
          configMap:
            name: {{ template "shja.fullname" . }}-script
        - name: crontab
          configMap:
            name: {{ template "shja.fullname" . }}-crontab
        - name: data
        {{- if .Values.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "shja.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
