#!/usr/bin/env ruby
$:.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

require 'shja'
require 'optparse'
require 'logger'

actor_urls = []

config = {}
config[:username]    = ENV['SHJA_USERNAME']
config[:password]    = ENV['SHJA_PASSWORD']
config[:target_dir]  = ENV['SHJA_TARGET_DIR']

parser = OptionParser.new

subparsers = Hash.new {|h,k|
  $stderr.puts "no such subcommand: #{k}"
  exit 1
}
subparsers['refresh'] = OptionParser.new
subparsers['refresh'].on('-u URL') {|v| actor_urls << v }

parser.order!(ARGV)
subcommand = ARGV.shift
subparsers[subcommand].parse!(ARGV) unless ARGV.empty?

unless config[:username] && config[:password] && config[:target_dir]
  raise "Required parameter is not specified: #{config}"
end

if subcommand == 'refresh'
  Shja.log.level = Logger::DEBUG
  client = Shja::Client::Hc.new(**config)
  actor_urls.each do |url|
    client.refresh_actor!(url)
  end
end
